### ISSUE TITLE
Application ?

### ISSUE THREAD

**Issue by francoismart** [sboily/node-red-contrib-wazo-platform#7]
hello
I'm playing with node-red and wazo, the config is ok but when I try to associate say web-socket or event to server config it's crashing on node side :

Error
    at Function.fromResponse (/***.node-red/node_modules/@wazo/sdk/dist/wazo-sdk.js:1:5174)
    at /***/.node-red/node_modules/@wazo/sdk/dist/wazo-sdk.js:3:5925
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /***/.node-red/node_modules/node-red-contrib-wazo-platform/nodes/event.js:72:26

I can see "applications" is empty in the dialog panel in node-red. So I have created an app on wazo platform side but doesn't appear neither in choices nor by default. 

Could you please let me know how to "see" my Node application inside "choose applications"  or if something is wrong on my side please ?

**Comment by sboily** [comment]
Hello, what is the version of node-red, wazo, and the plugin please.
